### ISSUE TITLE
Menu bugging then sticking on screen

### ISSUE THREAD

**Issue by Duskwood0585** [BarleyFlour/VisualAdjustments2#5] opened 2022-07-28 19:51 UTC
**Describe the bug**
There's a few times now where I click the visuals menu, and it appears in the middle of my screen, bugged out, sliders and buttons and all with no text on them. Then when I close the menu ...it stays there. In the middle of my screen. I have to turn the mod off, log back on, save, log out, and turn it back on.

**To Reproduce**
I can't say what is causing it. It seems to happen at completely random times.

**Expected behavior**
I expect to hit visuals, have the menu come up, and change things. But instead I get the above.

**Screenshots**

**Game Info:**
Unsure....the latest version on steam. I'm not sure how to tell.

**Comment by Duskwood0585** [comment] 2022-08-04 17:35
![image](https://user-images.githubusercontent.com/93407953/182914705-15411e40-c11e-437d-9936-964e5093e2cf.png)
Got a picture of it.

**Comment by RobMatteson** [comment] 2022-08-15 21:20
Seeing the same issue.

**Comment by BarleyFlour** [comment] 2022-08-16 10:04
Without reproduction steps its very hard for me to do much of anything, any such instructions would be appreciated.

**Comment by Darkfire11** [comment] 2022-08-17 20:22
I managed to reproduce in Act 1:
1. Go to Kenabres Map.  Bring up character menus and click on "Visual."  You'll see a blank screen (because the characters aren't currently rendered?)
2. Go into Defender's Heart and talk to Joran, ask to see his wares.
3. When you leave the shop screen, you'll get the bug.

**Comment by BarleyFlour** [comment] 2022-08-18 10:47
Fixed with 1.0.6, thanks for the reproduction steps.

**Closed by BarleyFlour** 2022-08-18 10:47 UTC
Labels: bug
